#!/bin/bash -xe

exec 2>&1

COUNTER=1
BACKEND_ADDR="http://{{bind.backend.first.sys.ip}}:{{bind.backend.first.cfg.port-http}}"
VAULT_ADDR="http://{{cfg.listener.location}}:{{cfg.listener.port}}"
VAULT_INIT="{{pkg.svc_files_path}}/unseal"

SEALED=$(curl -s http://0.0.0.0:8200/v1/sys/health | jq .sealed)

if [ "$SEALED" = true ] ; then
  # If vault is sealed, grab the keys out of the unseal file and unseal it
  cat ${VAULT_INIT} | grep '^Unseal' | awk '{print $4}' | for key in $(cat -); do
    vault operator unseal -address ${VAULT_ADDR} "$key"
    COUNTER=$((COUNTER + 1))
  done

else
  echo "Vault is already unsealed"
fi
